# Generated by Django 4.1.5 on 2023-02-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundalik',
            name='sarlavha',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
